# Cara Employee App Demo

# Dry run of CI script for Cara Employee App

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
# NPM (Node Package manager) to install npm and dependencies
# This will read the package.json file in the project file structure and find out the dependent plugins
- task: Npm@1
  inputs:
    command: 'install'

# Ionic commands
# first we build the source code (Js, html, typescript and angular)
- task: IonicCommand@1
  inputs:
    ionicCommand: 'build'
    ionicVersion: '5.4.14'
    cordovaVersion: '8.1.2'
# Now generate Android native code
- task: IonicCommand@1
  inputs:
    ionicCommand: 'cordova platform add android'
    ionicVersion: '5.4.14'
    cordovaVersion: '8.1.2'
# Now build android source and generate APK
# By default, the APK builds in Debug mode, we have to use --release argument to build it in release mode 
# That will need the location of the keystore file as well
- task: IonicCommand@1
  inputs:
    ionicCommand: 'cordova build android'
    ionicVersion: '5.4.14'
    cordovaVersion: '8.1.2'
# Generate iOS native code
- task: IonicCommand@1
  inputs:
    ionicCommand: 'cordova platform add ios'
    ionicVersion: '5.4.14'
    cordovaVersion: '8.1.2'
# Build APP for iOS using XCode via Cordova (unsigned). 
# ipa will be built when it is signed and published into AppStore  
- task: CordovaCommand@1
  inputs:
    cordovaCommand: 'build ios'
    cordovaVersion: '8.1.2'
# below section is for copying APK/APP to artifact
- task: CopyFiles@2
  inputs:
    contents: '**/*.app'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: drop 